# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\SME\OtherPrograms\Dynamic_Desktop_220809\qt_uis\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 633)
        MainWindow.setStyleSheet("background-color: #222225;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(30, 20, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("background:#F7D674;border-radius:5px;}QPushButton:hover{background:yellow;")
        self.toolButton.setObjectName("toolButton")
        self.visitButton = QtWidgets.QPushButton(self.centralwidget)
        self.visitButton.setGeometry(QtCore.QRect(600, 30, 15, 15))
        self.visitButton.setStyleSheet("background:#F7D674;border-radius:5px;}QPushButton:hover{background:yellow;")
        self.visitButton.setText("")
        self.visitButton.setObjectName("visitButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 490, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background:#F76677;border-radius:5px;}QPushButton:hover{background:red;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(630, 30, 15, 15))
        self.closeButton.setStyleSheet("background:#F76677;border-radius:5px;}QPushButton:hover{background:red;")
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 100, 511, 361))
        self.groupBox.setStyleSheet("background:#222225;color:white;border-radius:5px;}QPushButton:hover{background:#222225;color:skyblue")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 501, 341))
        self.label.setText("")
        self.label.setObjectName("label")
        self.videowidget = QVideoWidget(self.groupBox)
        self.videowidget.setGeometry(QtCore.QRect(40, 90, 192, 108))
        self.videowidget.setObjectName("videowidget")
        self.applyButton = QtWidgets.QPushButton(self.centralwidget)
        self.applyButton.setGeometry(QtCore.QRect(170, 490, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.applyButton.setFont(font)
        self.applyButton.setStyleSheet("background:#6DDF6D;border-radius:5px;}QPushButton:hover{background:green;")
        self.applyButton.setObjectName("applyButton")
        self.minimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.minimizeButton.setGeometry(QtCore.QRect(570, 30, 15, 15))
        self.minimizeButton.setStyleSheet("background:#6DDF6D;border-radius:5px;}QPushButton:hover{background:green;")
        self.minimizeButton.setText("")
        self.minimizeButton.setObjectName("minimizeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_2.setText(_translate("MainWindow", "关闭壁纸"))
        self.groupBox.setTitle(_translate("MainWindow", "预览"))
        self.applyButton.setText(_translate("MainWindow", "应用"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
